spring:
  aplication:
    name: 'rtrsServer'
  datasource:
    url: jdbc:postgresql://localhost:5432/rtrs
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      format_sql: true
passwordGenerator:
  passwordLength: 10